# Generated by Django 4.0.4 on 2022-06-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_cartitem_remove_cartproduct_product_user_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='user', to='ecommerce.cartitem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
